# version: '3.9'

# services:
#   app:
#     image: walkom-backend-app
#     container_name: walkom-backend-app
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8000:8000
#     volumes:
#       - ./.bin/:/root/
#       - ./configs/:/root/configs/
#     env_file:
#       - .env

version: '3.9'

services:
  api:
    image: b0shka/walkom-backend:stable
    container_name: walkom-api
    restart: always
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - 8000:8000
    environment:
      - MONGO_URI
      - MONGO_USER
      - MONGO_PASSWORD
      - FRONTEND_URL

  nginx:
    image: nginx:latest
    container_name: walkom-api-nginx
    restart: always
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./default.conf:/etc/nginx/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      nginx