version: '3.9'

services:
  api:
    image: b0shka/walkom-backend:stable
    container_name: walkom-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MONGO_URI
      - MONGO_DATABASE
      - EMAIL_SERVICE_NAME
      - EMAIL_SERVICE_ADDRESS
      - EMAIL_SERVICE_PASSWORD
      - SECRET_KEY