name: Release

on:
  push:
    branches:
      - main

env:
  REGISTRY: "b0shka"
  API_IMAGE: "walkom-api"
  TAG: "stable"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test project
        run: go test ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API image
        run: docker build -f deploy/Dockerfile -t ${REGISTRY}/${API_IMAGE}:${TAG} .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push API image to Docker Hub
        run: docker push ${REGISTRY}/${API_IMAGE}:${TAG}
      
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_and_push
    
  #   steps:
  #     - name: Deploy to Timeweb
  #       uses: appleboy/ssh-action@v0.1.8
  #       with:
